# Generated by go2rpm 1.7.0
%bcond_without check

# https://github.com/WireGuard/wireguard-go
%global goipath         golang.zx2c4.com/wireguard
%global forgeurl        https://github.com/WireGuard/wireguard-go
%global commit          c31a7b1ab47807f01613a571cc480f79d5fb4181

%gometa

%global common_description %{expand:
Mirror only. Official repository is at https://git.zx2c4.com/wireguard-go.}

%global golicenses      LICENSE
%global godocs          README.md examples

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Mirror only. Official repository is at https://git.zx2c4.com/wireguard-go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}
Patch0:         https://patch-diff.githubusercontent.com/raw/WireGuard/wireguard-go/pull/55.patch

%description
%{common_description}

%gopkg

%prep
%goprep
%patch0 -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/wireguard-go %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
rm format_test.go
%gocheck
%endif

%files
%license LICENSE
%doc README.md examples
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
