# Generated by go2rpm 1.7.0
%bcond_without check

# https://github.com/goreleaser/nfpm
%global goipath         github.com/goreleaser/nfpm
Version:                2.17.0

%gometa

%global common_description %{expand:
NFPM is Not FPM - a simple deb, rpm and apk packager written in Go.}

%global golicenses      LICENSE.md
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md SECURITY.md\\\
                        README.md docs

Name:           %{goname}
Release:        %autorelease
Summary:        NFPM is Not FPM - a simple deb, rpm and apk packager written in Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md SECURITY.md README.md docs
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
