# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/tailscale/hujson
%global goipath         github.com/tailscale/hujson
%global commit          54599719472fc1c68cb1c87e05cf10865a7489e5

%gometa

%global common_description %{expand:
HuJSON: JSON for Humans (JWCC: JSON w/ comments and trailing commas).}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        HuJSON: JSON for Humans (JWCC: JSON w/ comments and trailing commas)

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
