# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/tailscale/goexpect
%global goipath         github.com/tailscale/goexpect
%global commit          6e8c725cea41c34048c42bdeb0bd1a6fbf94995d

%gometa

%global common_description %{expand:
Expect for Go.}

%global golicenses      LICENSE
%global godocs          examples AUTHORS README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Expect for Go

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
