# Generated by go2rpm 1.7.0
# Skip tests as this temporary fork is just for one module
%bcond_with check
%global debug_package %{nil}

# https://github.com/tailscale/golang-x-crypto
%global goipath         github.com/tailscale/golang-x-crypto
%global commit          0b941c09a5e1d00a4aa9630ec59121f3e04e657e

%gometa

%global common_description %{expand:
(Tailscale dev fork for upstreaming to golang.org/x/crypto).}

%global golicenses      PATENTS LICENSE
%global godocs          AUTHORS CONTRIBUTING.md README.md CONTRIBUTORS

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        (Tailscale dev fork for upstreaming to golang.org/x/crypto)

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
