# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/fxamacker/cbor
%global goipath         github.com/fxamacker/cbor/v2
Version:                2.4.0

%gometa

%global common_description %{expand:
CBOR codec (RFC 8949) with CBOR tags, Go struct tags (toarray, keyasint,
omitempty), float64/32/16, big.Int, and fuzz tested billions of execs.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md CBOR_GOLANG.md\\\
                        SECURITY.md CBOR_BENCHMARKS.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        CBOR codec (RFC 8949) with CBOR tags, Go struct tags (toarray, keyasint, omitempty), float64/32/16, big.Int, and fuzz tested billions of execs

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
