# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/inetaf/netaddr
%global goipath         inet.af/netaddr
%global forgeurl        https://github.com/inetaf/netaddr
Version:                0.1
%global commit          09700637632167e91519bf5930d7ad004b796156

%gometa

%global common_description %{expand:
Network address types.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Network address types

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
