# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/x448/float16
%global goipath         github.com/x448/float16
Version:                0.8.4
%global commit          eaca6b03f609994e0febd680d639df290c45ef72

%gometa

%global common_description %{expand:
Float16 provides IEEE 754 half-precision format (binary16) with correct
conversions to/from float32.}

%global golicenses      LICENSE
%global godocs          SECURITY.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Float16 provides IEEE 754 half-precision format (binary16) with correct conversions to/from float32

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
