# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/go4org/unsafe-assume-no-moving-gc
%global goipath         go4.org/unsafe/assume-no-moving-gc
%global forgeurl        https://github.com/go4org/unsafe-assume-no-moving-gc
%global commit          928513b29760d736f52f4796ea3d4a6f5efe3886

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        None

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
