# Generated by go2rpm 1.7.0
%bcond_without check
%bcond_without bootstrap
%global debug_package %{nil}

# https://github.com/u-root/gobusybox
%global goipath         github.com/u-root/gobusybox
Version:                0.1.0
%global commit          85dc1fd1bc759b58405db41b84c381aeab70ff08

%gometa

%global goipaths0       github.com/u-root/gobusybox
%global goipathsex0     github.com/u-root/gobusybox/src/pkg/golang github.com/u-root/gobusybox/src/pkg/bb

%if %{without bootstrap}
%global goipaths1       github.com/u-root/gobusybox/src/pkg/golang github.com/u-root/gobusybox/src/pkg/bb
%endif

%global goaltipaths     github.com/u-root/gobusybox github.com/u-root/gobusybox/src/pkg/golang github.com/u-root/gobusybox/src/pkg/bb


%global common_description %{expand:
Tools for compiling many Go commands into one binary to save space. Builds are
supported in vendor-based Go, module-based Go, and bazel with Starlark.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Tools for compiling many Go commands into one binary to save space. Builds are supported in vendor-based Go, module-based Go, and bazel with Starlark

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  golang(github.com/google/goterm/term)
#BuildRequires:  golang(github.com/hugelgupf/p9/fsimpl/localfs)
#BuildRequires:  golang(github.com/hugelgupf/p9/p9)
%if %{without bootstrap}
#BuildRequires:  golang(github.com/u-root/u-root/pkg/strace)
BuildRequires:  golang(github.com/u-root/u-root/pkg/ulog)
%endif
BuildRequires:  golang(github.com/u-root/uio/cp)
BuildRequires:  golang(github.com/u-root/uio/ulog)
BuildRequires:  golang(golang.org/x/mod/modfile)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(golang.org/x/tools/go/ast/astutil)
BuildRequires:  golang(golang.org/x/tools/go/gcexportdata)
BuildRequires:  golang(golang.org/x/tools/go/packages)
BuildRequires:  golang(golang.org/x/tools/imports)

%description
%{common_description}

%gopkg

%prep
%goprep
# Avoid github.com/hugelgupf/p9
rm -rf test/nested/nestedmod
rm -rf test/nested/cmd/strace

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
