# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/toqueteos/webbrowser
%global goipath         github.com/toqueteos/webbrowser
Version:                1.2.0

%gometa

%global common_description %{expand:
:globe_with_meridians::snake: Python's webbrowser in Go. Simple API for opening
web pages on your default browser.}

%global golicenses      LICENSE.md
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        :globe_with_meridians::snake: Python's webbrowser in Go. Simple API for opening web pages on your default browser

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
