# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/u-root/u-root
%global goipath         github.com/u-root/u-root
Version:                0.9.0

%gometa

%global common_description %{expand:
A fully Go userland with Linux bootloaders! u-root can create a one-binary root
file system (initramfs) containing a busybox-like set of tools written in Go.}

%global golicenses      LICENSE
%global godocs          examples docs AUTHORS

Name:           %{goname}
Release:        %autorelease
Summary:        A fully Go userland with Linux bootloaders! u-root can create a one-binary root file system (initramfs) containing a busybox-like set of tools written in Go

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf cmds

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
