# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/u-root/u-root
%global goipath         github.com/u-root/u-root
Version:                0.9.0

%gometa

%global common_description %{expand:
A fully Go userland with Linux bootloaders! u-root can create a one-binary root
file system (initramfs) containing a busybox-like set of tools written in Go.}

%global golicenses      LICENSE
%global godocs          examples docs AUTHORS

Name:           %{goname}
Release:        %autorelease
Summary:        A fully Go userland with Linux bootloaders! u-root can create a one-binary root file system (initramfs) containing a busybox-like set of tools written in Go

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf cmds
rm -rf pkg/namespace pkg/fb

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
for test in "TestUrootCmdline" "TestParseDesc" "TestResolvePackagePaths" "TestCreateInitramfs"\
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck -d integration/generic-tests -d pkg/ldd -d pkg/pty -d pkg/strace -d pkg/syscallfilter -d pkg/uroot/builder
%endif

%gopkgfiles

%changelog
%autochangelog
