# Generated by go2rpm 1.7.0
%bcond_without check

# https://github.com/tailscale/goupnp
%global goipath         github.com/tailscale/goupnp
Version:                1.0.0
%global commit          66b27ba4e403bd6e4a23bce7cc896fe8ca779e10

%gometa

%global common_description %{expand:
Temporary working copy fork of huin/goupnp; a UPnP client library for Go
(#golang).}

%global golicenses      LICENSE
%global godocs          GUIDE.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Temporary working copy fork of huin/goupnp; a UPnP client library for Go (#golang)

License:        BSD-2-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc GUIDE.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
