# Generated by go2rpm 1.7.0
%bcond_without check

# https://github.com/hugelgupf/p9
%global goipath         github.com/hugelgupf/p9
Version:                0.2.0

%gometa

%global common_description %{expand:
Idiomatic Go 9P2000.L client and server, extracted from gVisor for general use.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Idiomatic Go 9P2000.L client and server, extracted from gVisor for general use

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
