# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/google/uuid
%global goipath         github.com/google/uuid
Version:                1.3.0

%gometa

%global common_description %{expand:
Go package for UUIDs based on RFC 4122 and DCE 1.1: Authentication and Security
Services.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md CONTRIBUTORS

Name:           %{goname}
Release:        %autorelease
Summary:        Go package for UUIDs based on RFC 4122 and DCE 1.1: Authentication and Security Services

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
