# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/go4org/netipx
%global goipath         go4.org/netipx
%global forgeurl        https://github.com/go4org/netipx
%global commit          3cc044ffd68d7671ca845d55957e9e570127dd28

%gometa

%global common_description %{expand:
Extra stuff from inet.af/netaddr that didn't make it into Go's net/netip.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Extra stuff from inet.af/netaddr that didn't make it into Go's net/netip

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
