# Generated by go2rpm 1.7.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/inetaf/peercred
%global goipath         inet.af/peercred
%global forgeurl        https://github.com/inetaf/peercred
%global commit          0893ea02156ae2c733c85cadbba588ac2045ce2d

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        None

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
