# Generated by go2rpm 1.7.0
%bcond_without check

# https://github.com/tailscale/tailscale
%global goipath         tailscale.com
%global forgeurl        https://github.com/tailscale/tailscale
Version:                1.28.0

%gometa

%global goname tailscale

%global common_description %{expand:
The easiest, most secure way to use WireGuard and 2FA.}

%global golicenses      PATENTS LICENSE tempfork/gliderlabs/ssh/LICENSE
%global godocs          docs AUTHORS CODE_OF_CONDUCT.md api.md SECURITY.md\\\
                        VERSION.txt ALPINE.txt README.md\\\
                        tempfork/pprof/README.md\\\
                        tempfork/gliderlabs/ssh/README.md example\\\
                        tstest/integration/vms/README.md words/scales.txt\\\
                        words/tails.txt example example logtail/api.md\\\
                        logtail/README.md cmd/tailscale/depaware.txt\\\
                        cmd/nginx-auth/README.md cmd/gitops-pusher/README.md\\\
                        cmd/tailscaled/depaware.txt

Name:           %{goname}
Release:        %autorelease
Summary:        The easiest, most secure way to use WireGuard and 2FA

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf internal/tooldeps
rm -rf cmd/mkpkg

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/tailscale cmd/tailscaled ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license PATENTS LICENSE tempfork/gliderlabs/ssh/LICENSE
%doc docs AUTHORS CODE_OF_CONDUCT.md api.md SECURITY.md VERSION.txt ALPINE.txt
%doc README.md tempfork/pprof/README.md tempfork/gliderlabs/ssh/README.md
%doc example tstest/integration/vms/README.md words/scales.txt words/tails.txt
%doc example example logtail/api.md logtail/README.md cmd/tailscale/depaware.txt
%doc cmd/nginx-auth/README.md cmd/gitops-pusher/README.md
%doc cmd/tailscaled/depaware.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
