# Generated by go2rpm 1.7.0
%bcond_without check

# https://github.com/tailscale/tailscale
%global goipath         tailscale.com
%global forgeurl        https://github.com/tailscale/tailscale
Version:                1.28.0

%gometa

%global goname tailscale

%global common_description %{expand:
The easiest, most secure way to use WireGuard and 2FA.}

%global golicenses      PATENTS LICENSE tempfork/gliderlabs/ssh/LICENSE
%global godocs          docs AUTHORS CODE_OF_CONDUCT.md api.md SECURITY.md\\\
                        VERSION.txt ALPINE.txt README.md\\\
                        tempfork/pprof/README.md\\\
                        tempfork/gliderlabs/ssh/README.md example\\\
                        tstest/integration/vms/README.md words/scales.txt\\\
                        words/tails.txt example example logtail/api.md\\\
                        logtail/README.md cmd/tailscale/depaware.txt\\\
                        cmd/nginx-auth/README.md cmd/gitops-pusher/README.md\\\
                        cmd/tailscaled/depaware.txt

Name:           %{goname}
Release:        %autorelease
Summary:        The easiest, most secure way to use WireGuard and 2FA

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  golang(github.com/anmitsu/go-shlex)
BuildRequires:  golang(github.com/aws/aws-sdk-go-v2/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go-v2/aws/arn)
BuildRequires:  golang(github.com/aws/aws-sdk-go-v2/config)
BuildRequires:  golang(github.com/aws/aws-sdk-go-v2/service/ssm)
BuildRequires:  golang(github.com/aws/aws-sdk-go-v2/service/ssm/types)
BuildRequires:  golang(github.com/coreos/go-iptables/iptables)
BuildRequires:  golang(github.com/coreos/go-systemd/activation)
BuildRequires:  golang(github.com/creack/pty)
BuildRequires:  golang(github.com/dave/jennifer/jen)
BuildRequires:  golang(github.com/fxamacker/cbor/v2)
BuildRequires:  golang(github.com/godbus/dbus/v5)
BuildRequires:  golang(github.com/golang/groupcache/lru)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/goreleaser/nfpm)
BuildRequires:  golang(github.com/goreleaser/nfpm/deb)
BuildRequires:  golang(github.com/goreleaser/nfpm/rpm)
BuildRequires:  golang(github.com/hdevalence/ed25519consensus)
BuildRequires:  golang(github.com/iancoleman/strcase)
BuildRequires:  golang(github.com/insomniacslk/dhcp/dhcpv4)
BuildRequires:  golang(github.com/jsimonetti/rtnetlink)
BuildRequires:  golang(github.com/kballard/go-shellquote)
BuildRequires:  golang(github.com/klauspost/compress/zstd)
BuildRequires:  golang(github.com/kortschak/wol)
BuildRequires:  golang(github.com/mdlayher/genetlink)
BuildRequires:  golang(github.com/mdlayher/netlink)
BuildRequires:  golang(github.com/mdlayher/sdnotify)
BuildRequires:  golang(github.com/mitchellh/go-ps)
BuildRequires:  golang(github.com/peterbourgon/ff/v3/ffcli)
BuildRequires:  golang(github.com/pkg/sftp)
BuildRequires:  golang(github.com/skip2/go-qrcode)
BuildRequires:  golang(github.com/tailscale/golang-x-crypto/ssh)
BuildRequires:  golang(github.com/tailscale/goupnp)
BuildRequires:  golang(github.com/tailscale/goupnp/dcps/internetgateway2)
BuildRequires:  golang(github.com/tailscale/hujson)
BuildRequires:  golang(github.com/tailscale/netlink)
BuildRequires:  golang(github.com/tcnksm/go-httpstat)
BuildRequires:  golang(github.com/toqueteos/webbrowser)
BuildRequires:  golang(github.com/u-root/u-root/pkg/termios)
BuildRequires:  golang(go4.org/mem)
BuildRequires:  golang(golang.org/x/crypto/acme)
BuildRequires:  golang(golang.org/x/crypto/acme/autocert)
BuildRequires:  golang(golang.org/x/crypto/argon2)
BuildRequires:  golang(golang.org/x/crypto/blake2s)
BuildRequires:  golang(golang.org/x/crypto/chacha20poly1305)
BuildRequires:  golang(golang.org/x/crypto/curve25519)
BuildRequires:  golang(golang.org/x/crypto/hkdf)
BuildRequires:  golang(golang.org/x/crypto/nacl/box)
BuildRequires:  golang(golang.org/x/crypto/ssh)
BuildRequires:  golang(golang.org/x/net/dns/dnsmessage)
BuildRequires:  golang(golang.org/x/net/http2)
BuildRequires:  golang(golang.org/x/net/http2/h2c)
BuildRequires:  golang(golang.org/x/net/proxy)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(golang.org/x/term)
BuildRequires:  golang(golang.org/x/time/rate)
BuildRequires:  golang(golang.org/x/tools/go/packages)
BuildRequires:  golang(golang.org/x/tools/imports)
BuildRequires:  golang(golang.zx2c4.com/wireguard/conn)
BuildRequires:  golang(golang.zx2c4.com/wireguard/device)
BuildRequires:  golang(golang.zx2c4.com/wireguard/tun)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/refs)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/adapters/gonet)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/buffer)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/header)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/link/channel)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/network/ipv4)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/network/ipv6)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/stack)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/transport/icmp)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/transport/tcp)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/tcpip/transport/udp)
BuildRequires:  golang(gvisor.dev/gvisor/pkg/waiter)
BuildRequires:  golang(inet.af/netaddr)
BuildRequires:  golang(inet.af/peercred)
BuildRequires:  golang(nhooyr.io/websocket)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/aws/aws-sdk-go-v2/feature/s3/manager)
BuildRequires:  golang(github.com/aws/aws-sdk-go-v2/service/s3)
BuildRequires:  golang(github.com/frankban/quicktest)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
BuildRequires:  golang(github.com/google/uuid)
BuildRequires:  golang(github.com/miekg/dns)
BuildRequires:  golang(github.com/tailscale/goexpect)
BuildRequires:  golang(github.com/vishvananda/netlink)
BuildRequires:  golang(golang.org/x/net/nettest)
BuildRequires:  golang(golang.org/x/sync/semaphore)
BuildRequires:  golang(golang.zx2c4.com/wireguard/tun/tuntest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf internal/tooldeps
rm -rf cmd/mkpkg

%build
for cmd in cmd/tailscale cmd/tailscaled ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license PATENTS LICENSE tempfork/gliderlabs/ssh/LICENSE
%doc docs AUTHORS CODE_OF_CONDUCT.md api.md SECURITY.md VERSION.txt ALPINE.txt
%doc README.md tempfork/pprof/README.md tempfork/gliderlabs/ssh/README.md
%doc example tstest/integration/vms/README.md words/scales.txt words/tails.txt
%doc example example logtail/api.md logtail/README.md cmd/tailscale/depaware.txt
%doc cmd/nginx-auth/README.md cmd/gitops-pusher/README.md
%doc cmd/tailscaled/depaware.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
